# Generated by Django 6.0.4 on 2026-05-05 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='regprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNumber', models.CharField(blank=True, max_length=10)),
                ('preference', models.CharField(choices=[('LB', 'Pound'), ('ER', 'Euro'), ('YE', 'Yen'), ('YU', 'Yuan')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
